### PR TITLE
Add from_tsv and write_tsv

### PR DESCRIPTION
**Pull request by mrkn**
TSV format is popular to export/import tabular data as well as CSV format.
So I think we should have `write_tsv` and `from_tsv`.

### CODE REVIEW

**Comment by gnilrets** [comment]
Seems a little redundant to me.  Whenever I hear "CSV" I automatically think any delimited text file, whether it be comma, tab, pipe, semicolon, whatever.....

**Comment by zverok** [comment]
@gnilrets As I am saying in the review, convenience method `DataFrame#from_tsv` underlining "we can do this" is OK, but I am not sure about adding new functionality to `IO`

**Comment by v0dro** [comment]
@mrkn don't you think its best to use `col_sep:` option for `from_csv`?

**Comment by zverok** [comment]
@v0dro In public interface, I think it is OK to have `from_csv`/`from_tsv` just as an indicator "we can do that" (not everyone aware of the fact that Ruby's CSV library in fact is able to handle {Anything}SeparatedValues)

**Comment by mrkn** [comment]
There are two options, I think.

1. Following @zverok opinion, remove new methods from `IO` and rewrite new methods in `DataFrame`.
2. Withdraw this pull-request.

I want to follow the development policy of this project.
I like the former, but the latter is also OK for me.

@v0dro How do you think?

**Comment by v0dro** [comment]
There can be a shortcut method called `from_tsv` but I think all the major logic should lie in `from_csv` with a `col_sep:` option.

**Comment by zverok** [comment]
@mrkn I believe we have a consensus here. Would you mind finalizing the PR so we can merge and prosper?

**Pull request closed without merging**
