### PR TITLE
[WIP] Benchmarking Daru::Vector statistics methods

### PR DESCRIPTION
**Pull request by Shekharrajak**
I think we should continue this idea : https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2017-Ideas#rewrite-slow-parts-of-daru-in-rubex

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Comparing benchmark : https://github.com/SciRuby/daru/wiki/Benchmark-comparison-daru-vs-pandas-&-numpy

**Comment by v0dro** [comment]
Good thought. However, I think we should move to benchmark-ips for the benchmarking: https://github.com/evanphx/benchmark-ips

It provides much more accurate benchmarks and the comparisons will not vary too much between machines.

**Comment by v0dro** [comment]
Also, can you please use 2 spaces for all indentation in your code?

**Comment by Shekharrajak** [comment]
I have compared various ways (using Array of array, array of vector, Hash of array , Hash of vector) of initializing `Daru::DataFrame` in this [wiki page ](https://github.com/SciRuby/daru/wiki/Benchmark-Daru::DataFrame-Initialize-method)

**Pull request closed without merging**
