### PR TITLE
Fixes in DateTimeIndex, Vector and Index related to working with empty indexes

### PR DESCRIPTION
**Pull request by Phitherek**
There are quite a few changes, they all came to light when I was debugging my project. The tests are passing fine. Let me know if there is any problem.

### CODE REVIEW

**Comment by v0dro** [comment]
Great! Could you also add test cases that would actually run these edge cases so that future contributors will readily know when something goes wrong?

**Comment by v0dro** [comment]
@Phitherek are you still working on this?

**Comment by Phitherek** [comment]
@v0dro I'm sorry, I don't have much time right now but I remember about it and I will certainly write some tests for this when I find time.

**Comment by v0dro** [comment]
@Phitherek have you had the time to write tests for this? I'd like to merge these fixes before the next release, which is due soon. Tests will also pave the way for discussion if the features you've introduced are in the spirit of the library as a whole.

**Comment by Phitherek** [comment]
@v0dro Sorry, I haven't found time yet... When are you planning to release the next version?

**Comment by v0dro** [comment]
As soon as a few fixes that I'm waiting for are ready, which should be early next week. One spec per fix should be enough.

**Comment by v0dro** [comment]
Outdated.

**Pull request closed without merging**
