### PR TITLE
Update Daru::DateTimeIndex.new slice error

### PR DESCRIPTION
**Pull request by weqopy**
Data like `dt = Daru::DateTimeIndex.new(['2021-09-01','2021-09-02'])`
image

PR fix:
image

### CODE REVIEW

**Comment by weqopy** [comment]
Would you please to help check this PR? @zverok

**Comment by zverok** [comment]
Unfortunately, it seems there are no active maintainers for the library. 
(I personally left the SciRuby organization 3 years ago and have no resource for daru.)
I am afraid it should be considered abandoned by this point.

**Comment by kojix2** [comment]
Among the data frames in the Ruby language, [rover](https://github.com/ankane/rover) is actively maintained. You probably know that. But rover may not seem to have the ability to handle dates...

**Comment by weqopy** [comment]
Thanks for your response and your work before, though. @zverok

**Pull request closed without merging**
