### PR TITLE
Replace is_nil?, not_nil?

### LINKED ISSUE #141: [API] Rename Vector#is_nil?
As the method not returns boolean (the only thing that predicate methods should return), it definitely shouldn't contain question mark in the name.

So, my proposal here is `#is_nil?` => `#nils`, `#not_nil?` => `#not_nils`.

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #141 

Replaces Vector#is_nil? and Vector#not_nil? with something else.

### CODE REVIEW

**Comment by v0dro** [comment]
How about `include_values?` and `not_include_values?`? That way it's consistent with `Array#include?` and the extra `_values` conveys that the behavior differs a little from the `Array#include?`.  @zverok?

**Comment by zverok** [comment]
What it will return? If arrays of booleans -- then I still don't think that "predicate method sign" (`?`) is appropriate.

**Comment by v0dro** [comment]
@zverok it will return arrays of booleans. Yeah it makes sense to not have the `?`.

**Comment by zverok** [comment]
Hey, guys, are we going to finalize this eventually? :) I think that we can at least go with `nils`/`not_nils` or `existance(*values)`/`non_existance(*values)`. Or whatever!

**Comment by v0dro** [comment]
Yeah lets stick with `include_values`.

**Comment by lokeshh** [comment]
We already have `include_values?` to return `true` and `false`. I think it will be confusing to have `include_values`. Lets's have `is_values`. It also signifies that we are checking if the value is the same as what we are mentioning.

**Comment by v0dro** [comment]
> We already have include_values? to return true and false. I think it will be confusing to have include_values. Lets's have is_values. It also signifies that we are checking if the value is the same as what we are passing as argument, "include" could be confusing here. WDYT

Ah yes. `is_values?` seems like a good choice. @zverok ?

**Comment by zverok** [comment]
To be honest, I like neither, but can't come with a better name :) So, let's go with `is_values`!

**Comment by v0dro** [comment]
Works. `is_values?` is the way to go.

**Comment by zverok** [comment]
Just without question mark, I thought we've agreed on that ;)

**Comment by v0dro** [comment]
@lokeshh can you fix this? The PR is quite old.

**Comment by lokeshh** [comment]
Done finally. No more delay :)

**Pull request merged**
