### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by laser-shark**
I noticed some warnings about these unused variables while using daru in a project and wanted to remove them. :)

### CODE REVIEW

**Comment by kojix2** [comment]
As you can see in the Travis CI test results, this variable is used in ERB. That's why you can't delete this variable. But it doesn't mean there's no need for improvement. 
If Rubocop misunderstands the variables are not used, it's probably not good for humans to read too.

**Comment by laser-shark** [comment]
Sorry, I didn't realize this!  I guess it's not that hard to understand for someone who knows ERB. To be honest, I don't really have an idea on how to make this better, other than maybe disabling the rubocop rule for these methods?

**Comment by Shekharrajak** [comment]
> Sorry, I didn't realize this! I guess it's not that hard to understand for someone who knows ERB. To be honest, I don't really have an idea on how to make this better, other than maybe disabling the rubocop rule for these methods?

These variables are needed.

**Comment by Shekharrajak** [comment]
Please let me know if you need more clarification.

**Comment by v0dro** [comment]
Closing due to inaction.

**Pull request closed without merging**
